vich_uploader:
    db_driver: orm

    mappings:
       works_of_art:
           uri_prefix: '%app.path.works_of_art%'
           upload_destination: '%kernel.project_dir%/public/%app.path.works_of_art%'
